export const SET_LISTS = 'SET_LISTS';
export const SET_PERIOD = 'SET_PERIOD';
export const SET_ORG_OID = 'SET_ORG_OID';
export const SET_ORG_NAME = 'SET_ORG_NAME';
export const SET_FILTERS_DEFAULT = 'SET_FILTERS_DEFAULT';
export const SET_SHOW_FILTERS = 'SET_SHOW_FILTERS';
export const SET_SERVICE_OID = 'SET_SERVICE_OID';
export const SET_SELECTED_KTL = 'SET_SELECTED_KTL';
export const SET_SELECTED_WORKERS = 'SET_SELECTED_WORKERS';

